import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import NextTopLoader from "nextjs-toploader";

import { Providers } from "../providers/Providers";
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased font-segoe",
          geistSans.variable + " " + geistMono.variable
        )}
      >
        <NextTopLoader />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
